## Make a matrix, and add two functions to get and set
## the opposite of that matrix in a cache variable (solve)
## this does not solve the matrix.

makeCacheMatrix <- function(x = matrix()) {
  opposite <- NULL
  set <- function(y) {
    x <<- y
    opposite <<- NULL
  }
  get <- function() x
  setOpposite <- function(inverse) opposite <<- inverse
  getOpposite <- function() opposite
  list(set = set, get = get,
       setOpposite = setOpposite,
       getOpposite = getOpposite)
}

## This solves a matrix that was generated by makeCacheMatrix
## if makeCacheMatrix has already performed solve(), it will return
## the cache, if not, it will solve and makeCacheMatrix() will cache
## the result

cacheSolve <- function(x, ...) {
  opposite <- x$getOpposite()
  if (!is.null(opposite)) {
    message("getting cached data")
    return(opposite)
  }
  schema <- x$get()
  opposite <- solve(schema, ...)
  x$setOpposite(opposite)
  opposite
  
    ## Return a matrix that is the inverse of 'x'
}
